enum PropriedadesPermission {
	LER_PROPRIEDADES = 'LER_PROPRIEDADES',
	MODIFICAR_PROPRIEDADES = 'MODIFICAR_PROPRIEDADES',
	MODIFICAR_PROPRIEDADES_ADMIN = 'MODIFICAR_PROPRIEDADES_ADMIN'
}
   
export default PropriedadesPermission;