enum UsuarioPermission {
	LER_USUARIO_CLIENTE = 'LER_USUARIO_CLIENTE',
	LER_USUARIO = 'LER_USUARIO',
	MODIFICAR_USUARIO = 'MODIFICAR_USUARIO',
	MODIFICAR_USUARIO_PUBLIC = 'MODIFICAR_USUARIO_PUBLIC',
	MODIFICAR_USUARIO_CLIENTE = 'MODIFICAR_USUARIO_CLIENTE'
}
   
export default UsuarioPermission;